aircraft:
  name: "Airbus A350-1000"
  empty_weight_kg: 155000
  Max_takeoff_weight_kg: 316000
  empty_cg_arm_m: 28.9
  mac_length_m: 7.5
  lemac_m: 30
  cg_fwd_limit_pct_mac: 25
  cg_aft_limit_pct_mac: 36
  max_payload_kg: 51000

zones:

  # ── Forward belly hold — LD3 positions ──────────────────────────────────────
  - id: FWD_01
    description: Forward hold  position 
    hold: FWD
    arm_m: 15
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)
            # max_gross - tare
  - id: FWD_02
    description: Forward hold  position 
    hold: FWD
    arm_m: 17
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2) 

   id: FWD_03
    description: Forward hold  position 
    hold: FWD
    arm_m: 19
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)

   id: FWD_04
    description: Forward hold  position 
    hold: FWD
    arm_m: 21
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)  
  # ── Aft belly hold — ULD positions ──────────────────────────────────────
- id: AFT-01
    description: Aft hold ULD position 01
    hold: AFT
    arm_m: 31
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)
- id: AFT-02
    description: Aft hold ULD position 01
    hold: AFT
    arm_m: 33
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)
- id: AFT-03
    description: Aft hold ULD position 01
    hold: AFT
    arm_m: 35
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)
- id: AFT-04
    description: Aft hold ULD position 01
    hold: AFT
    arm_m: 37
    uld_tare_kg: (82+120) / 2  # Average tare for LD3 and PMC
    max_gross_kg: 1200        # tare + cargo combined
    max_cargo_kg: 1200 - ((82+120) / 2)
  # ── Aft belly hold — ULD positions ──────────────────────────────────────
- id: BULK
    hold: BULK
    uld_type: BULK
    arm_m: 40
    uld_tare_kg: 0
    max_cargo_kg: 600